/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import conexao.conexao;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class TelaEmprestimo extends javax.swing.JFrame {
   
    conexao con_cliente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName());

    /**
     * Creates new form Tela1
     */
    public TelaEmprestimo() {
        initComponents();
        con_cliente = new conexao();
        con_cliente.conecta();
        
        con_cliente.executaSQL("select * from tbclientes order by cod");
preencherTabela();
posicionarRegistro();
jTable1.setAutoCreateRowSorter(true);// ativa a classificação ordenada da tabela
    }
public void preencherTabela() {

    jTable1.getColumnModel().getColumn(0).setPreferredWidth(4);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(11);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(4);
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setNumRows(0);

    try {

        con_cliente.resultset.beforeFirst();

        while (con_cliente.resultset.next()) {

            modelo.addRow(new Object[]{
              con_cliente.resultset.getString("cod")
                    ,con_cliente.resultset.getString("nome")
                    ,con_cliente.resultset.getString("dt_nasc"
                    ),con_cliente.resultset.getString("telefone")
                    , con_cliente.resultset.getString("email")
            });
        }

    } catch (SQLException erro) {
      JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        
    }
}
public void posicionarRegistro() {
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
        mostrar_Dados(); // chama o método que irá buscar o dado da tabela
    } catch (SQLException erro) {
       JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}
public void mostrar_Dados() {
    try {

        codigot.setText(con_cliente.resultset.getString("cod")); // Associar a caixa de texto ao campo cod
        nomet.setText(con_cliente.resultset.getString("nome")); // Associar a caixa de texto ao campo nome
        datat.setText(con_cliente.resultset.getString("dt_nasc"));
        telefonet.setText(con_cliente.resultset.getString("telefone"));
        emailt.setText(con_cliente.resultset.getString("email"));

    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

    int linha_selecionada = jTable1.getSelectedRow();

    codigot.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
    nomet.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
    datat.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
    telefonet.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
    emailt.setText(jTable1.getValueAt(linha_selecionada, 4).toString());

}
private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {

    // evento que sincroniza a grid com as setas do teclado

    int linha_selecionada = jTable1.getSelectedRow();

    codigot.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
    nomet.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
    datat.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
    telefonet.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
    emailt.setText(jTable1.getValueAt(linha_selecionada, 4).toString());

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        codigot = new javax.swing.JTextField();
        nomet = new javax.swing.JTextField();
        datat = new javax.swing.JTextField();
        telefonet = new javax.swing.JTextField();
        emailt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nascimento", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        codigo.setText("Código:");

        nome.setText("Nome:");

        data.setText("Data Nascimento:");

        telefone.setText("Telefone:");

        email.setText("Email");

        emailt.addActionListener(this::emailtActionPerformed);

        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo)
                            .addComponent(nome)
                            .addComponent(data)
                            .addComponent(telefone)
                            .addComponent(email))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigot, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomet)
                            .addComponent(datat)
                            .addComponent(telefonet)
                            .addComponent(emailt, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(codigot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(nomet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data)
                    .addComponent(datat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(telefonet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        con_cliente.resultset.first();
        mostrar_Dados();
    } catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível acessar o primeiro registro: "+erro);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
        con_cliente.resultset.previous();
        mostrar_Dados();
    } catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no registro anterior: "+erro);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        con_cliente.resultset.next();
        mostrar_Dados();
    } catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no próximo registro: "+erro);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try {
        con_cliente.resultset.last();
        mostrar_Dados();
    } catch(SQLException erro){
        JOptionPane.showMessageDialog(null,"Não foi possível posicionar no último registro: "+erro);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEmprestimo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigot;
    private javax.swing.JLabel data;
    private javax.swing.JTextField datat;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomet;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField telefonet;
    // End of variables declaration//GEN-END:variables
}
